name: EC2-Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@ec2-deploy-test.yanap-apptest.tk '
          cd /home/ec2-user &&
          git clone https://github.com/YanaPIIDXer/EC2DeployTest.git &&
          cat EC2DeployTest/README.md &&
          rm -rf EC2DeployTest
          '
